a = input("Digite algo: ")
print("O tipo primitivo desse valor é ", type(a))
print("Só tem espaços ?", a.isspace())
print("É um numero ?", a.isnumeric())
print("É alfabetico ?", a.isalpha())
print("É alfanumerico ?", a.isalnum())
print("Está em letras minusculas ?", a.islower())
print("Ésta em letras maiusculas ?", a.isupper())
print("Está capitalizada ?", a.istitle())
